### ISSUE TITLE
Bug in read_pbm_binary

### ISSUE THREAD

**Issue by pierre-dejoue** [ToruNiina/pnm#2]
Hi there!

Great job on the library ! I've started using it on my project [picross-solver](https://github.com/pierre-dejoue/picross-solver). I noticed two issues which I fixed on my fork of [pnm](https://github.com/pierre-dejoue/pnm): 

- [x] missing include `<cctype>` needed for `std::isspace` (I saw it compiling with MSVC)
- [x] issue in `read_pbm_binary` when the image's width is a multiple of 8

I loaded a 56x39 pbm image. The width happens to be a multiple of 8. In that case pnm++ reads one extra byte per line in the image.

Let me know if you'd like a pull request for those patches, or if you prefer to patch those yourself. They are trivial anyway!

**Comment by ToruNiina** [comment]
Thank you for reporting the issue!
Pull requests are always welcome. If it is okay with you, could you send the pull request?

**Comment by ToruNiina** [comment]
Merged. Thank you again!
